buckets = [
    [1, 1, 2, 3, 3, 2, 2, 3, 4, 3, 3, 4, 4, 4, 5, 5, 5],
    [2, 3, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
    [0, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1],
    [0, 0, 2, 1, 1, 2, 2, 3, 2, 3, 3, 4, 4, 4, 3, 3, 3],
    [0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 3, 3, 3, 2, 1, 1],
    [0, 0, 2, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5],
]

tests = [
    [
        False,
        True,
        True,
        None,
        False,
        None,
        True,
        True,
        False,
        None,
        True,
        None,
        None,
        True,
        None,
        None,
    ],
    [
        True,
        True,
        None,
        True,
        None,
        None,
        None,
        True,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ],
    [
        False,
        False,
        True,
        None,
        False,
        False,
        False,
        False,
        False,
        False,
        True,
        None,
        False,
        False,
        False,
        False,
    ],
    [
        None,
        True,
        False,
        False,
        True,
        None,
        True,
        False,
        True,
        None,
        True,
        None,
        None,
        False,
        None,
        None,
    ],
    [
        None,
        False,
        False,
        False,
        False,
        False,
        False,
        False,
        True,
        None,
        True,
        None,
        None,
        False,
        False,
        False,
    ],
    [
        None,
        True,
        True,
        None,
        True,
        None,
        None,
        None,
        True,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    ],
]


terms_to_add = {1: 3}
